name: Github Actions Workload Identity Federation
'on':
  push:
    branches:
      - main
  pull_request:
    branches: main
jobs:
  print:
    runs-on: ubuntu-latest
    environment: dev # Fetches the env variables for dev
    permissions:
      id-token: write
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: '${{ secrets.GITHUB_TOKEN }}'
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ vars.WORKLOAD_IDENTITY_POOL }}'

  build:
    runs-on: ubuntu-latest
    environment: dev # Fetches the env variables for dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: '${{ vars.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: set credentials file
        run: >-
          gcloud auth login
          --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Use gcloud CLI
        run: gcloud info
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: CHANGELOG.md
          destination: mahendran-data-proc-input-data/
          process_gcloudignore: false
